version: '3.8'

services:
  jekyll:
    build: .
    container_name: jekyll-dev
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll
      - bundle_cache:/usr/local/bundle
    environment:
      - JEKYLL_ENV=development
    command: bundle exec jekyll serve --host 0.0.0.0 --port 4000 --livereload --force_polling
    stdin_open: true
    tty: true

  # Alternative service using official Jekyll image
  jekyll-official:
    image: jekyll/jekyll:4
    container_name: jekyll-official-dev
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll
      - bundle_cache_official:/usr/local/bundle
    environment:
      - JEKYLL_ENV=development
    command: jekyll serve --host 0.0.0.0 --port 4000 --livereload --force_polling
    stdin_open: true
    tty: true

volumes:
  bundle_cache:
  bundle_cache_official: