name: Deploy to GitHub Pages

on:
  workflow_run:
    workflows: ["Build Jekyll Sites"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download mypage artifact
        uses: actions/download-artifact@v4
        with:
          name: mypage-site
          path: mypage

      - name: Download everyday artifact
        uses: actions/download-artifact@v4
        with:
          name: everyday-site
          path: everyday

      - name: Prepare deployment folder
        run: |
          mkdir -p public/mypage
          cp -r mypage/* public/mypage/

          mkdir -p public/everyday
          cp -r everyday/* public/everyday/

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
