name: Build and Deploy Jekyll Themes

on:
  push:
    branches: [gh-pages]
  workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # grants write permission for repo contents

    steps:

      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # フル履歴取得（pushのために必要）

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1  # 必要に応じて変更

      - name: Install Bundler
        run: gem install bundler

      - name: Build Theme 1
        working-directory: mypage
        run: |
          bundle install
          bundle exec jekyll build --destination ../../mypage

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        working-directory: mypage        
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./mypage/_site
          publish_branch: gh-pages
          force_orphan: true      # 履歴クリアして強制上書き
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com                    

      - name: Build Theme 2
        working-directory: everyday
        run: |
          bundle install
          bundle exec jekyll build --destination ../../everyday

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_PAT }}          
          publish_dir: ./everyday/_site
          publish_branch: gh-pages
          force_orphan: true      # 履歴クリアして強制上書き
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com          
          

      # - name: Push to gh-pages
      #   run: |
      #     git config user.name "github-actions"
      #     git config user.email "github-actions@github.com"
      #     git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}
      #     git add -A
      #     git commit -m "Update site" || echo "Nothing to commit"
      #     git push origin gh-pages


