name: Build Jekyll Sites

on:
  push:
    branches: [gh-pages]
  workflow_dispatch:

jobs:
  build_mypage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
      - name: Install dependencies
        run: |
          cd mypage
          bundle install
      - name: Build mypage
        run: |
          cd mypage
          bundle exec jekyll build -d ../build/mypage
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mypage-site
          path: build/mypage/

  build_everyday:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
      - name: Install dependencies
        run: |
          cd everyday
          bundle install
      - name: Build everyday
        run: |
          cd everyday
          bundle exec jekyll build -d ../build/everyday
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: everyday-site
          path: build/everyday/
