name: Build and Deploy Jekyll Themes

on:
  push:
    branches: [gh-pages]
  workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1  # 必要に応じて変更

      - name: Install Bundler
        run: gem install bundler

      - name: Build Theme 1
        working-directory: mypage
        run: |
          bundle install
          bundle exec jekyll build --destination ../../mypage

      - name: Build Theme 2
        working-directory: everyday
        run: |
          bundle install
          bundle exec jekyll build --destination ../../everyday

      - name: Push to gh-pages
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}
          git add -A
          git commit -m "Update site" || echo "Nothing to commit"
          git push origin gh-pages
